name: Go CI

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  test-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.16"

      - name: Download dependencies
        working-directory: ./frontend
        run: go mod download

      - name: Build frontend
        working-directory: ./frontend
        run: go build -v .

      - name: Test frontend
        working-directory: ./frontend
        run: go test -v ./...

      - name: Run go vet
        working-directory: ./frontend
        run: go vet ./...

  test-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.16"

      - name: Download dependencies
        working-directory: ./backend
        run: go mod download

      - name: Build backend
        working-directory: ./backend
        run: go build -v .

      - name: Test backend
        working-directory: ./backend
        run: go test -v ./...

      - name: Run go vet
        working-directory: ./backend
        run: go vet ./...

  linting:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Super-Linter
        uses: super-linter/super-linter/slim@v8
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_DOCKERFILE: true
          VALIDATE_YAML: true