name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

env:
  NAMESPACE: student-10

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Configure kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > "${{ runner.temp }}/kubeconfig"
          chmod 600 "${{ runner.temp }}/kubeconfig"
          echo "KUBECONFIG=${{ runner.temp }}/kubeconfig" >> "$GITHUB_ENV"

      - name: Ensure namespace exists
        run: |
          kubectl get ns "$NAMESPACE" >/dev/null 2>&1 || kubectl create ns "$NAMESPACE"

      - name: Deploy application
        run: |
          kubectl -n "$NAMESPACE" apply -f ./kubernetes/redis-deployment.yaml
          kubectl -n "$NAMESPACE" apply -f ./kubernetes/backend-deployment.yaml
          kubectl -n "$NAMESPACE" apply -f ./kubernetes/frontend-deployment.yaml

      - name: Wait for deployment
        run: |
          kubectl -n "$NAMESPACE" rollout status deploy/redis --timeout=300s
          kubectl -n "$NAMESPACE" rollout status deploy/backend --timeout=300s
          kubectl -n "$NAMESPACE" rollout status deploy/frontend --timeout=300s

  test:
    runs-on: ubuntu-latest
    needs: deploy
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config

      - name: Make test script executable
        run: chmod +x ./test-app.sh

      - name: Test application availability
        run: ./test-app.sh "${{ env.NAMESPACE }}"