name: deployment

on:
  workflow_dispatch:
    
  push:
    branches: [ "main" ]

jobs:
  kubernetes:
    runs-on: ubuntu-latest
    env:
      NAMESPACE: student-10  

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Write kubeconfig and export path
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > "${{ runner.temp }}/kubeconfig"
          chmod 600 "${{ runner.temp }}/kubeconfig"
          echo "KUBECONFIG=${{ runner.temp }}/kubeconfig" >> "$GITHUB_ENV"
      - name: Sanity check cluster/context
        run: |
          kubectl config current-context
          kubectl cluster-info
      - name: Ensure namespace exists
        run: |
          kubectl get ns "$NAMESPACE" >/dev/null 2>&1 || kubectl create ns "$NAMESPACE"
      - name: Deploy manifests
        run: |
          kubectl -n "$NAMESPACE" apply -f ./kubernetes/backend-deployment.yaml
          kubectl -n "$NAMESPACE" apply -f ./kubernetes/frontend-deployment.yaml
      - name: Verify rollout
        run: |
          kubectl -n "$NAMESPACE" get deployments
          kubectl -n "$NAMESPACE" rollout status deploy/backend --timeout=180s
          kubectl -n "$NAMESPACE" rollout status deploy/frontend --timeout=180s
  
  smoke_test:
    runs-on: ubuntu-latest
    env:
      NAMESPACE: student-10  
      FRONTEND_SVC: frontend
      BACKEND_SVC: backend
      FRONT_LOCAL: 8080
      BACK_LOCAL: 9000
    steps:
      - name: Smoke Test in-cluster
        run: |
          kubectl -n "$NAMESPACE" run smoke-test --rm -it \
            --image=curlimages/curl --restart=Never -- \
            sh -c "curl -fsS http://$BACKEND_SVC:9000/health && curl -fsS http://$FRONTEND_SVC:8080/health"