name: Go CI

on:
  pull_request:
    branches: [ "main" ] # Kør CI på PRs mod main
  push:
    branches: [ "main" ] # Valgfrit: også kør på direkte pushes til main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout koden
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Sæt Go op
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22" # Skift til din Go-version

      # 3. Download dependencies (fra repo-roden)
      - name: Download dependencies
        run: go mod download

      # 4. Build frontend
      - name: Build frontend
        run: go build -v ./frontend

      # 5. Build backend
      - name: Build backend
        run: go build -v ./backend

      # 6. Run frontend tests
      - name: Test frontend
        run: go test -v ./frontend/...

      # 7. Run backend tests
      - name: Test backend
        run: go test -v ./backend/...
