name: Go CI

on:
  pull_request:
    branches: [ "main" ]  # Run CI on PRs targeting main
  push:
    branches: [ "main" ]  # Optional: also run CI on direct pushes to main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      
    - name: Checkout
      uses: actions/checkout@v4

      
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.16" 


    - name: Build frontend
      run: go build -v ../frontend

      
    - name: Build backend
      run: go build -v ../backend
      
    - name: Run tests
      run: go test -v ./...
