name: Go CI

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Use the Go version declared in the frontend go.mod (change path if needed)
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: skibidi-fortune-cookie/frontend/go.mod
          cache: true

      - name: Build frontend
        working-directory: skibidi-fortune-cookie/frontend
        run: go build -v ./...

      - name: Test frontend
        working-directory: skibidi-fortune-cookie/frontend
        run: go test -v ./...

      # Build backend only if it is a separate module (has its own go.mod)
      - name: Build backend (if module exists)
        working-directory: skibidi-fortune-cookie/backend
        run: |
          if [ -f go.mod ]; then
            go build -v ./...
          else
            echo "No go.mod in skibidi/backend; skipping backend build."
          fi

      - name: Test backend (if module exists)
        working-directory: skibidi-fortune-cookie/backend
        run: |
          if [ -f go.mod ]; then
            go test -v ./...
          else
            echo "No go.mod in skibidi/backend; skipping backend tests."
          fi


