name: Release

on:
  push:
    tags: ["v*.*.*"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
           ghcr.io/${{ github.repository_owner }}/skibidi-fortune-cookie-backend:${{ github.ref_name }}
           ghcr.io/${{ github.repository_owner }}/skibidi-fortune-cookie-backend:latest
      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
           ghcr.io/${{ github.repository_owner }}/skibidi-fortune-cookie-frontend:${{ github.ref_name }}
           ghcr.io/${{ github.repository_owner }}/skibidi-fortune-cookie-frontend:latest