name: Release

on:
  push:
    branches: ["main"]

env:
  OWNER: kongkrog1

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Scan Docker Image
        uses: aquasecurity/trivy-action@v0.29.3
        with:
          image-ref: myorg/myapp:latest

      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.OWNER }}/skibidi-fortune-cookie-backend:${{ github.ref_name }}
            ghcr.io/${{ env.OWNER }}/skibidi-fortune-cookie-backend:latest

      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.OWNER }}/skibidi-fortune-cookie-frontend:${{ github.ref_name }}
            ghcr.io/${{ env.OWNER }}/skibidi-fortune-cookie-frontend:latest
