name: Release

on:
  push:
    tags:
      - 'v*'

env:
  OWNER: kongkrog1

jobs:
  test-docker:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test Docker application
        run: |
          docker compose up --build -d
          sleep 30
          chmod +x ./testing/test-docker.sh
          ./testing/test-docker.sh

      - name: Cleanup test environment
        if: always()
        run: docker compose down -v

  build-images:
    runs-on: ubuntu-latest
    needs: test-docker
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build backend image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: false
          tags: |
            ghcr.io/${{ env.OWNER }}/skibidi-fortune-cookie-backend:${{ steps.version.outputs.VERSION }}
            ghcr.io/${{ env.OWNER }}/skibidi-fortune-cookie-backend:latest

      - name: Build frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: false
          tags: |
            ghcr.io/${{ env.OWNER }}/skibidi-fortune-cookie-frontend:${{ steps.version.outputs.VERSION }}
            ghcr.io/${{ env.OWNER }}/skibidi-fortune-cookie-frontend:latest

  push-images:
    runs-on: ubuntu-latest
    needs: build-images
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.OWNER }}/skibidi-fortune-cookie-backend:${{ steps.version.outputs.VERSION }}
            ghcr.io/${{ env.OWNER }}/skibidi-fortune-cookie-backend:latest

      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.OWNER }}/skibidi-fortune-cookie-frontend:${{ steps.version.outputs.VERSION }}
            ghcr.io/${{ env.OWNER }}/skibidi-fortune-cookie-frontend:latest